### ISSUE TITLE
Connexion impossible 

### ISSUE THREAD

**Issue by rfautier** [pvarry/intra42#10]
Hello, déjà merci pour l'appli, elle est bien pratique ^^
J ai changer de portable et installer le appli. Ne recevant pas de notification (toute les autorisations étais au vert) , je l ai desinstaller puis re-installer
Sauf que maintenant je peux plus me connecter, j ai le message `chain validation failed`
Je suis sur Android 8.0 avec chrome comme navigateur
Je sais pas si ça vient de moi ou pas
Si tu as besoin de plus de Info ou tu as une solution, tu peux me contacter par slack, j y répond plus vite en général (rfautier)
Bonne journée !

**Comment by pvarry** [comment]
Salut,

J'ai un problème de certificat SSL sur le serveur d'authentification.
Ce sera fix d'ici peu de temps

Concernant le problème avec les notifications, le service qui les gère est normalement lancé, mais ne fonctionne pas comme il le faudrait, il faut que je regarde d'ou ça vient.
Ce sera fix le plus tôt possible.

**Comment by rfautier** [comment]
Je peux me connecter de nouveau , merci !
