### ISSUE TITLE
App crashes when editing map

### ISSUE THREAD

**Issue by mehdibo** [pvarry/intra42#13]
I just added a new cluster, saved it, when I click on "edit map" for that cluster the app crashes. editing other clusters' maps is working fine.

**Comment by pvarry** [comment]
I found the bug and fixed it. It will be available in days.

It crash because the map is empty (and null) and it try to get values on this object. I can manually create a map for a desired cluster, do you want to edit a cluster before the update ?

**Comment by mehdibo** [comment]
I want to add my campus's map, I'm not sure how your app works for the map editing, do I need to wait for update to be able to add the map or is there another way?

**Comment by pvarry** [comment]
Yes, is a another way. I save the map on a extenal server, and I can init the cluster map to avoid crash (untill update)

**Comment by mehdibo** [comment]
If that's possible then It's a good solution, I'll then edit the map

**Comment by pvarry** [comment]
Witch cluster you want to edit ?

**Comment by mehdibo** [comment]
Campus: Khouribga (id: 16)
Full name: Stage 1
I'm planning to add another cluster too, the second cluster.

**Comment by pvarry** [comment]
You can now edit this cluster without crash (no not leave a empty map until next release)

**Comment by mehdibo** [comment]
It's working, thanks
