### ISSUE TITLE
impossible de se connecter après mise à jour cnil

### ISSUE THREAD

**Issue by lgarczyn** [pvarry/intra42#16]
J'ai essayé d'utiliser l'appli ce matin, mais certaines fonctionnalités ne marchaient pas. J'ai reset l'application, mais maintenant il est impossible de se login. Quand je clique mon browser flash, puis je retourne à l'application. Une snack-bar vide apparaît quelques secondes.

Essayé avec firefox android and chromium.

**Comment by pvanderl** [comment]
Cela doit être dû aux nouvelles reglementations de 42 pour la mise à jour de mot de passe ? :)

**Comment by pvarry** [comment]
Salut, j'ai deja recu un mail d'un autre utilisateur concernant ce problème et je vais essayer de régler le probleme ce soir. Je penses qu'ils ont mis a jours l'API et que quelque chose est soit cassé soit ne fonctionne plus de la meme manière.

**Comment by msabwat** [comment]
Pour ma part, une désinstallation suivie d'une réinstallation a résolu le problème. A condition bien sur d'avoir reset le mdp. Ça doit être une erreur de cache ?

**Comment by pvarry** [comment]
> Pour ma part, une désinstallation suivie d'une réinstallation a résolu le problème. A condition bien sur d'avoir reset le mdp. Ça doit être une erreur de cache ?

Tu viens de le faire a l'instant ? J'ai modifier un truc sur le serveur d'auth

**Comment by msabwat** [comment]
Ah ! Oui, je l'ai fait vers 09h/09h30
