### ISSUE TITLE
Event notifications are not leading to the right event

### ISSUE THREAD

**Issue by fassn** [pvarry/intra42#24]
Whenever I receive a notification for a new event at 42, if I click on the notification tab to know more about it, it doesn't get me on the page of the right event. It brings me on the page of another event.
Phone: Samsung Galaxy A5
![20191029_201028](https://user-images.githubusercontent.com/4950521/67800854-55978380-fa88-11e9-9b7d-5dcb7d704858.png)
![Screenshot_20191029-200814](https://user-images.githubusercontent.com/4950521/67800855-56301a00-fa88-11e9-90cf-ffd36f355c59.png)

**Comment by pvarry** [comment]
Hello, I just fixed this issue https://github.com/pvarry/intra42/commit/752d28e0a9492e63b00d1778ff053a85fb95d6a8

A release will be rolled out next few days
