### ISSUE TITLE
new 42cursus holy graph not available

### ISSUE THREAD

**Issue by thefullarcticfox** [pvarry/intra42#27]
![image](https://user-images.githubusercontent.com/8538211/83792106-42463980-a6a3-11ea-9803-1550182cfff5.png)
![image](https://user-images.githubusercontent.com/8538211/83800244-d0c0b800-a6af-11ea-9033-011a4b51bbe9.png)

**Comment by jplot** [comment]
Hi Ivan,
Could you tell me your login and campus?

**Comment by thefullarcticfox** [comment]
oh nevermind. it's working now

**Comment by nikonakoneko** [comment]
since the first day i used it it never worked here. ablanken @ 42barcelom
