### ISSUE TITLE
SSL Handshake aborted: ssl=0x........: I/O error during system call, connection reset by peer

### ISSUE THREAD

**Issue by jerem-ma** [pvarry/intra42#33]
Hey !
I get the error `SSL Handshake aborted: ssl=0x........: I/O error during system call, connection reset by peer` when I try to login to the application, just after pushing the button "Authorize" on the oauth part of the intra to authorize `Intranet for Android` to access to some data. Is it possible to fix it ? Thanks !

**Comment by jplot** [comment]
Hi Jérémy,
We are currently performing a server migration, the problem will be solved by the end of the week.

Have a nice day,
Jonathan

**Comment by jerem-ma** [comment]
Excellent, thanks !

**Comment by pvarry** [comment]
Hello Jérémy,
The server migration is now done and it must work again.
Thanks you for waiting.

Regards,
Paul
