### ISSUE TITLE
"Unable to connect to internet" while loading friends

### ISSUE THREAD

**Issue by jerem-ma** [pvarry/intra42#34]
Hello !
There is the error "Unable to connect to internet" when I try to see the friends I added to the app. Other panels like cluster map, agenda, slots, evaluations or the profile page of someone, work without any problem.
The friends list are not stocked directly in the phone ?
Thank you for your app, have a nice day !

**Comment by jplot** [comment]
Hi Jérémy,
We are currently experiencing a breakdown on our servers, we are trying to solve the problem as soon as possible.
Concerning the management of friends, the data is stored on a server.

**Comment by jplot** [comment]
Hi,
We had a lot of problems with the server change.
Everything should be back to normal now.
