### ISSUE TITLE
[FEAT REQUEST] Add bug report button into the app

### ISSUE THREAD

**Issue by avallete** [pvarry/intra42#4]
Would be great to easily bug-report from the app. 

Like the ticket creator system from the real-intra. 

Can also be useful to join internal app debug logs (all the requests performed and the status, the traceback of all function call from the launching of app) when a new ticket is created.

**Comment by pvarry** [comment]
When the app crash, a bug report is automatically send through Firebase, no data are sent just the stack of function.

I may add a way to dump log to clipboard or file for UI problems and other bugs like that.

**Comment by pvarry** [comment]
Added in about menu
