### ISSUE TITLE
Fail to login

### ISSUE THREAD

**Issue by AlphaBril** [pvarry/intra42#42]
![Screenshot_20230102_174807_Intra 42](https://user-images.githubusercontent.com/29873870/210259508-a634f47e-a061-481b-91d9-d8b81fa92431.jpg)
After a complete reset of cache and data on android
![Screenshot_20230102_174957_Software update](https://user-images.githubusercontent.com/29873870/210259662-9d50fefc-f2a9-4c67-b82d-1284d32cb00d.jpg)
I can no longer log into the app after being logged into the 42 api.

**Comment by jplot** [comment]
Hi,
I will correct the problem tonight.
