### ISSUE TITLE
Search is bugged

### ISSUE THREAD

**Issue by Njiallu** [pvarry/intra42#7]
When something is already searched, and you type something and press enter the search appears to not be working (at least on the beta), not updating.

**Comment by pvarry** [comment]
Salut, je n'ai pas reussi a reproduire ton probleme en beta (0.8.4-beta3), cepandant j'ai trouve un petit bug graphique lié a la recherche. Si ce probleme est toujours present dans la derniere version beta n'hesite pas a repondre en indiquant la version de l'application, tu télèphone et la procedure pour reproduire le bug.

**Comment by Njiallu** [comment]
okay la version 3 le règle 👍
