### ISSUE TITLE
impossible to retrieve the galaxy's data.

### ISSUE THREAD

**Issue by sreouven** [pvarry/intra42#8]
Impossible de récupérer la nouvelle galaxie (graphiquement) et les nouveaux projets.
Meme si on suscribe aux nouveaux projets, ils n'apparaissent pas non plus.

**Comment by pvarry** [comment]
Depuis qu'il ont modifié la galaxie il y a quelques jours, l'affichage de la galaxie dans mon app est buggé. Le problème est fix et j'ai une mise à jour en attente. Mai comme j'ai un problème avec le nombre de requêtes par seconde je dois voir un truc avec de publier cet maj. 

En attendant tu peux aller sur le Home et refresh les données pour afficher les projets aux quel tu est souscrit

**Comment by sreouven** [comment]
Pas réussi, je suis beta testeur de l'app mais rien de mon coté.
Bon courage pour fix ce bug ;)
