### ISSUE TITLE
Voir les levels  sur la carte 

### ISSUE THREAD

**Issue by lgarczyn** [pvarry/intra42#9]
Une option pour overlay les niveaux des étudiants  sur la carte des clusters. Ça permettrait d'aider à trouver des groupes de gens de son niveau quand ton groupe est pas là, au lieu de s'assoir seul

**Comment by pvarry** [comment]
Tres bonne idée !!
J'ai demendé a l'intra team d'ajouter un filtre pour pouvoir recuperer cette information en peux de temps.

stay tuned

**Comment by Seluj78** [comment]
Ça serait aussi intéressant d'avoir une feature comme dans https://peers.extends42.fr

**Comment by pvarry** [comment]
Salut, sa aussi j'ai voulu l'ajouter mais le problème est le même que pour les niveaux, il n'est pas possible de filtrer les données de l'API avec tous les filtres que l'on veut, comme les niveaux des users ou le statut d'un projet. C'est pour sa que je dois trouver une autre solution mais je n'abandonne pas 😃. J'espère vous le sortir le plus vite possible

**Comment by lgarczyn** [comment]
Salut, tu as pu avancer ? Il y a pas moyen de juste charger le profile de chaque étudiant connecté?

**Comment by pvarry** [comment]
Non, je ne peut rien faire dans l'etat des choses, charger ce genre de donnée (le profile de chaque étudiant connecté) prendrait environ 10min quand le cluster est plein.

**Comment by lgarczyn** [comment]
Vraiment ? J'ai regarder l'API, tu peux sort les user d'un cursus avec les dates de fin prévu ascendantes, et juste request les users par pages de 100, avec le niveau inclus. 

Je trouve pas ce que renvoie la requête de cluster users, je suppose qu'elle ne contient pas le niveau si on en est là.

**Comment by pvarry** [comment]
En effet on peux sort les users en fonction de plusiers criteres mais le niveau n'en fait pas partie. Lorsque l'on fait cet request (le cluster map ou les users) on obtient juste une liste de login, il est donc pas possible de faire un tri coté front. Le trie en fonction de la date de fin de cursus n'est disponible que pour les users qui ont fini 42 ou qui sont close, ce qui n'est pas d'une tres grande utilité

Le seul moyen que je vois actuellement c'est d'utiliser une base de donnée externe mais ce n'est pas possible dans l'imediat

**Comment by lgarczyn** [comment]
La request de cursus renvoie le niveau

**Comment by pvarry** [comment]
Quel route ?

**Comment by lgarczyn** [comment]
https://api.intra.42.fr/apidoc/2.0/cursus_users/index.html

**Comment by pvarry** [comment]
En effet, je vais regarder

**Comment by pvarry** [comment]
Bonjour, grace a @lgarczyn, j'ai pu ajouter les niveaux sur le map.

Une nouvelle version est disponible sur le Play Store (en beta pour le moment, vous devez souscrire aux betas pour y avoir access). Les traductions ne sont pas encore faites. 

Faites vos retours sur ce que vous en penser.

**Comment by lgarczyn** [comment]
J'ai testé un peu, un scan de student du cursus 42 de niveau 0-21+ ne donne rien.

Quand j'ai changé le cursus vers piscine décloisonée et updaté les info, l'app a crashé.

Une fois que j'ai restart, ça marche, mais seulement 4-7 student sont affiché comme étant de niveau 0-21+ sur la piscine décloisonné (j'ai trouvé plusieurs niveaux 5-6 qui n'était pas surlignés).

L'app crash systématiquement en chargeant la piscine à distance, j'ai envoyé un report par google play.

Ensuite question design, un overlay avec le niveau affiché en petit serait plus pratique.

**Comment by pvarry** [comment]
Merci du retour
J'ai remarqué le crash, j'ai reçu un report automatique (il n'est pas obligatoire d'envoyer le rapport)
Le fait que les utilisateurs ne soit pas correctement affiché viens de l'option "close".
Je vais voir comment ajouter le niveau directement sur la map.

Prochaine version mercredi dans la journée

**Comment by lgarczyn** [comment]
Je suis pas sûr que c'est le close, j'ai trouvé des profile non-close qui faisait parti du cursus 42 et qui s'affichait pas, même avec l'option "afficher les cursus close".

**Comment by pvarry** [comment]
Depuis quelques jours une nouvelle version est disponible en beta, j'attends vos retours

**Comment by lgarczyn** [comment]
Hnnnng

**Comment by lgarczyn** [comment]
C'est parfait

**Comment by lgarczyn** [comment]
C'est encore mieux que ce que j'imaginais, merci!

L'ergonomie est toujours pas top, mais je sais pas comment l'améliorer. Avoir une liste des filtres récemment utilisés, et des suggestions par défaut? Fait réfléchir si ça vaut la peine, mais ça reste super.

**Comment by pvarry** [comment]
Merci, moi aussi je n'aime pas trop le choix initial du filtre mais je vais un petit peu y réfléchir. En attendant c'est publié

**Comment by lgarczyn** [comment]
J'ai encore des personnes non surlignées. 

En e1 nboulaye est niveau 16, mais il apparaît pas sur une recherche "cursus 42" avec les close inclus ou pas.

Pour en trouver d'autre, fait juste une recherche de gens qui ont finit leur stage, la plupart ne semble pas inclus.

Sinon si je tape "first-internship" dans la barre de recherche de projet, il me trouve le projet "we think code first internship" sans me donner le choix.

**Comment by pvarry** [comment]
L'autre problème qui gens qui n'apparaissent pas viens du fait que certains sont inscrits a plusieurs cursus (piscine et 42 par exemple) et du coup cela dépasse la taille de la page. Pour régler ce problème soit je fais le double d'appel a l'API soit je demande un rafraîchissement des données a chaque fois que le cursus est changé (je vais certainement faire le 2eme solution).

Je vais regarder pour les projets, actuellement il fonctionne mieux quand tu tapes seulement une partie du nom, je vais l'améliorer pour les slugs

**Comment by lgarczyn** [comment]
Tu ne peux pas juste charger plus d'une pages? Si il y a plus de 100 personnes connectés ça sera nécessaire.

**Comment by lgarczyn** [comment]
Perso il y a toujours 0 student au dessus du niveau 10 d'affiché, ça enlève pas mal d'utilité au système.

**Comment by pvarry** [comment]
Bonjour, depuis une semaine, une nouvelle version est en ligne et je voulais savoir si tu as eu le temps de regarder les changements ?

**Comment by lgarczyn** [comment]
Pas eu de problèmes pour l'instant, je continue de checker.
